### ISSUE TITLE
Add date of access to Recommended Citation

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#24]
Below shows the current Recommended citation on Project detail pages.
Please add after "Accessed" the current date from web page, formatted in ISO YYYY-MM-DD

![Firefox_Screenshot_2020-04-02T15-58-06 887Z](https://user-images.githubusercontent.com/2523089/78270987-742efa00-74c0-11ea-982c-fb83869d5368.png)

**Comment by birbjam** [comment]
So it's supposed to be doing that automatically but for some projects that data is not there or displayed as XX-XX-XXXX

**Comment by mkoo** [comment]
I think a little js  could grab the date from when the page loads to insert "today's date"
we're just trying to make it easy for people to copy/paste the citation if they are going to use the data. Also the format could be yyyy-mm-dd but this is the current one:

![Firefox_Screenshot_2020-04-02T16-27-31 774Z](https://user-images.githubusercontent.com/2523089/78273897-477ce180-74c4-11ea-9b3b-053fed5151ba.png)

**Comment by birbjam** [comment]
Ohh I see. Add current date and update with each visit?

**Comment by birbjam** [comment]
Okay I added date accessed that updates every time the project is accessed but it does kind of conflict with some of the displayed data still, when I fetch the project data for some of the projects, this is what I get:
![Screen Shot 2020-04-02 at 11 09 54 AM](https://user-images.githubusercontent.com/41635757/78283548-c8db7080-74d2-11ea-882c-4995fa19f6d2.png)

(Click on screenshot to view in full screen otherwise too tiny)

![Screen Shot 2020-04-02 at 11 11 31 AM](https://user-images.githubusercontent.com/41635757/78283569-d1cc4200-74d2-11ea-85a3-7e00b846697a.png)

There might be a way to fix this on my end but I haven't figured it out yet.
Maybe there is a way to fix this on the GEOME end?

**Comment by mkoo** [comment]
FYI, closing issues automatically moves it to the Done column in the Project!
