### ISSUE TITLE
comments on Species Dashboard

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortal#58]
thoughts on recently released:
![Firefox_Screenshot_2020-06-06T16-30-34 258Z](https://user-images.githubusercontent.com/2523089/83949425-8b4bda00-a7d8-11ea-8da3-8f568c0cf1a5.png)

- I like the more organized view and prefer having the pie charts in Bd and Bsal columns; perhaps if there is no data for the pathogen, then a note: "No data exists". Also 4 columns might be too crowded
- Not sure the 3rd column Total Sampled is needed-- seems to take up needed room. I would prefer to remove and have Total Samples noted below the piecharts: " XXX Total Samples were tested for Bd"
- Also is there a minimum threshold of data to produce a piechart? See https://amphibiandisease.org/dashboard/?id=Amolops+chunganensis
- I look forward to links to the Project Detail pages in the last column!

**Comment by birbjam** [comment]
- I am trying to figure out how to display something like "No Bd/Bsal Data Available" when that is the case but I've been having some issues with that. I'll keep working on it.

- The Totals Sampled column is helpful when there is both Bd and Bsal collected, so you can see the ratio of Bd to Bsal collected. Ex: https://amphibiandisease.org/dashboard/?id=Alytes+obstetricans
  But I can take it out and replace with text under the pie charts.
- The minimum threshold of data to produce a chart is 1 Positive 1 Negative results per pathogen. If all are negative, it just displays text as it didn't make sense to me to display a pie chart where 100% of the results are negative.. I can totally change that though.

**Comment by birbjam** [comment]
Okay so it will now show 'No Bd/ Bsal data available' if it does not exist and I changed the code to display pie charts even if there are no positive results so it would be visually more consistent (and less confusing). 
  Also changed up the layout of the dashboard itself so that Associated Projects will display below the charts to free up some real estate so its not so crowded. I'll wait to push these changes to master until we can touch base tomorrow.
